### ISSUE TITLE
请教Modtran

### ISSUE THREAD

**Issue by liangfengyouxingii** [Tatjanaya/Create_MODTRAN5_tape5#2]
您好，我想使用Modtran建立一个特定传感器的透射率与大气水汽含量的模型。
关于TIGR2000大气廓线数据，您可以提供它的官方说明手册readme.tigr2000_v1.2_43_lev.doc吗。我申请了两次该数据的下载，TIGR都没有给我回复。

**Comment by Tatjanaya** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tatjanaya/Create_MODTRAN5_tape5"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月18日(星期二) 中午11:33
收件人:&nbsp;"Tatjanaya/Create_MODTRAN5_tape5"<Create_MODTRAN5_tape5@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Tatjanaya/Create_MODTRAN5_tape5] 请教Modtran (#2)





 
您好，我想使用Modtran建立一个特定传感器的透射率与大气水汽含量的模型。
 关于TIGR2000大气廓线数据，您可以提供它的官方说明手册readme.tigr2000_v1.2_43_lev.doc吗。我申请了两次该数据的下载，TIGR都没有给我回复。

**Comment by Tatjanaya** [comment]
发一个flt文件，格式按这个来，MODTRAN说明书里有示例。邮件被当成骚扰邮件放到垃圾邮箱了hhh，只能找前面的邮件回复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tatjanaya/Create_MODTRAN5_tape5"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月18日(星期二) 中午11:33
收件人:&nbsp;"Tatjanaya/Create_MODTRAN5_tape5"<Create_MODTRAN5_tape5@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Tatjanaya/Create_MODTRAN5_tape5] 请教Modtran (#2)





 
Closed #2.

**Comment by liangfengyouxingii** [comment]
您好，请问您可以将您的Sentinel3_SLSTR_S8.flt文件还有TIGR的大气廓线相关数据分享一份给我吗，特别是readme.TIGR2000_v1.2_43_lev.doc文档。我自己申请了3次，都没有给我回复。万分感谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tatjanaya/Create_MODTRAN5_tape5"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 下午4:14
收件人:&nbsp;"Tatjanaya/Create_MODTRAN5_tape5"<Create_MODTRAN5_tape5@noreply.github.com&gt;;
抄送:&nbsp;"凉风有兴"<1362723810@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Tatjanaya/Create_MODTRAN5_tape5] 请教Modtran (#2)





 发一个flt文件，格式按这个来，MODTRAN说明书里有示例。邮件被当成骚扰邮件放到垃圾邮箱了hhh，只能找前面的邮件回复 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Tatjanaya/Create_MODTRAN5_tape5"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年8月18日(星期二) 中午11:33 
 收件人:&amp;nbsp;"Tatjanaya/Create_MODTRAN5_tape5"<Create_MODTRAN5_tape5@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [Tatjanaya/Create_MODTRAN5_tape5] 请教Modtran (#2) 
 
 
 
 
 
   
 Closed #2.
